// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview AI-powered job category suggestion flow.
 *
 * - suggestJobCategories - A function that suggests job categories for a job posting.
 * - SuggestJobCategoriesInput - The input type for the suggestJobCategories function.
 * - SuggestJobCategoriesOutput - The return type for the suggestJobCategories function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestJobCategoriesInputSchema = z.object({
  jobTitle: z.string().describe('The title of the job posting.'),
  jobDescription: z.string().describe('The description of the job posting.'),
});

export type SuggestJobCategoriesInput = z.infer<typeof SuggestJobCategoriesInputSchema>;

const SuggestJobCategoriesOutputSchema = z.object({
  categories: z
    .array(z.string())
    .describe('An array of suggested job categories for the job posting.'),
});

export type SuggestJobCategoriesOutput = z.infer<typeof SuggestJobCategoriesOutputSchema>;

export async function suggestJobCategories(input: SuggestJobCategoriesInput): Promise<SuggestJobCategoriesOutput> {
  return suggestJobCategoriesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestJobCategoriesPrompt',
  input: {schema: SuggestJobCategoriesInputSchema},
  output: {schema: SuggestJobCategoriesOutputSchema},
  prompt: `You are a job categorization expert. Given the job title and description below, suggest relevant job categories.  Return the categories as a JSON array of strings.

Job Title: {{{jobTitle}}}
Job Description: {{{jobDescription}}}`,
});

const suggestJobCategoriesFlow = ai.defineFlow(
  {
    name: 'suggestJobCategoriesFlow',
    inputSchema: SuggestJobCategoriesInputSchema,
    outputSchema: SuggestJobCategoriesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
